# Generated by Django 4.2.6 on 2023-11-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_additionalimage_id_alter_advuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='bb',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='price',
        ),
        migrations.AddField(
            model_name='advuser',
            name='account_add_resume',
            field=models.BooleanField(default=True, verbose_name='Аккаунт для добавления резюме (поиск работы)'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='account_add_vacancy',
            field=models.BooleanField(default=True, verbose_name='Аккаунт для добавления вакансии (для работодателей)'),
        ),
        migrations.AddField(
            model_name='bb',
            name='education',
            field=models.CharField(choices=[('SO', 'Среднее'), ('SPO', 'Среднее-профессиональное (СПО)'), ('VO', 'Высшее (ВО)')], default='Среднее-профессиональное', max_length=40, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='bb',
            name='email',
            field=models.EmailField(default='example@mail.ru', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='bb',
            name='empoloyment_area',
            field=models.CharField(default='Не указан', max_length=150, verbose_name='Район трудоустройства'),
        ),
        migrations.AddField(
            model_name='bb',
            name='experience',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='bb',
            name='salary_from',
            field=models.IntegerField(default='0', verbose_name='Зарплата от'),
        ),
        migrations.AddField(
            model_name='bb',
            name='salary_up_to',
            field=models.IntegerField(default='0', verbose_name='Зарплата до'),
        ),
        migrations.AddField(
            model_name='bb',
            name='schedule',
            field=models.CharField(choices=[('FE', 'Полная занятость'), ('FS', 'Гибкий график'), ('SW', 'Сменный график'), ('FT', 'Скользящий график'), ('BD', 'Разрывной график'), ('SM', 'Вахтовый метод'), ('AN', 'Другое')], default='Полная занятость', max_length=40, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='bb',
            name='telephone',
            field=models.CharField(default='Не указан', max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацию?'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subrubric', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='SuperRubric',
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Надрубрика',
                'verbose_name_plural': 'Надрубрики',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.rubric',),
        ),
    ]
