# Generated by Django 4.2.6 on 2023-11-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bb_options_remove_bb_contacts_remove_bb_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='account_add_resume',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='account_add_vacancy',
        ),
        migrations.AddField(
            model_name='advuser',
            name='account_type',
            field=models.CharField(choices=[('NO', ''), ('VAC', 'Вакансии'), ('RES', 'Резюме')], default='Среднее-профессиональное', max_length=40, verbose_name=''),
        ),
    ]
