# Generated by Django 4.2.6 on 2023-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_advuser_account_add_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='account_type',
            field=models.CharField(choices=[('NO', ''), ('VAC', 'Вакансии'), ('RES', 'Резюме')], default='RES', max_length=10, verbose_name='Тип учётной записи'),
        ),
    ]
