# Generated by Django 4.2.6 on 2023-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_advuser_account_add_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='account_type',
            field=models.CharField(choices=[('VAC', 'Вакансии'), ('RES', 'Резюме')], default='RES', max_length=100, verbose_name='Тип учётной записи'),
        ),
    ]
