# Generated by Django 4.2.6 on 2023-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_advuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='account_type',
            field=models.CharField(choices=[('NO', ''), ('VAC', 'Вакансии'), ('RES', 'Резюме')], default='RES', max_length=20, verbose_name='Тип учётной записи'),
        ),
    ]
