# Generated by Django 4.2.6 on 2023-12-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bb_account_bb_name_contact_bb_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='account_type',
        ),
        migrations.AddField(
            model_name='advuser',
            name='account_add_resume',
            field=models.BooleanField(default=False, verbose_name='Аккаунт для добавления резюме (поиск работы)'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='account_add_vacancy',
            field=models.BooleanField(default=False, verbose_name='Аккаунт для добавления вакансии (для работодателей)'),
        ),
    ]
